apiVersion: v1
kind: PersistentVolume
metadata:
  name: kuard-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/on/host # Replace with the actual path on your host machine

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuard-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      volumeMounts:
        - name: kuard-data
          mountPath: /data

  volumes:
    - name: kuard-data
      persistentVolumeClaim:
        claimName: kuard-data
